name: MartysSpawnerUpgrade
version: 1.0
author: croyke
Website: http://martycraft.net
main: play.martycraft.net.main
commands:
  msu:
    description: The main command for the martysSpawnerUpgrade plugin
permissions:
  UpgradeGUI.use:
    description: Allows you to open the spawner upgrade menu with right click on a spawner
    default: op

